"use client";

import { motion } from "framer-motion";
import { Scale, FileText, AlertCircle, CheckCircle } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="bg-black text-zinc-400 min-h-screen pt-32 pb-24">
      <section className="relative py-20 overflow-hidden border-b border-white/5">
        <div className="container mx-auto px-4 md:px-6 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex flex-col items-center text-center max-w-3xl mx-auto"
          >
            <div className="w-16 h-16 bg-blue-500/10 rounded-2xl flex items-center justify-center mb-8 border border-blue-500/20">
              <Scale className="w-8 h-8 text-blue-400" />
            </div>
            <h1 className="text-4xl md:text-6xl font-bold mb-6 tracking-tighter text-white">
              Terms of Service
            </h1>
            <div className="flex items-center space-x-2 text-blue-400/60 uppercase tracking-widest text-xs font-bold">
               <FileText className="w-4 h-4" />
               <span>Effective Date: December 26, 2025</span>
            </div>
          </motion.div>
        </div>
      </section>

      <section className="py-24">
        <div className="container mx-auto px-4 md:px-6 max-w-4xl">
          <div className="space-y-16">
            <motion.div
               initial={{ opacity: 0, y: 20 }}
               whileInView={{ opacity: 1, y: 0 }}
               viewport={{ once: true }}
               className="space-y-6"
            >
              <h2 className="text-2xl font-bold text-white flex items-center">
                <span className="text-blue-500 mr-3">01.</span> Agreement to Terms
              </h2>
              <div className="prose prose-zinc prose-invert max-w-none font-light leading-relaxed text-lg text-zinc-400">
                <p>
                  By deploying our autonomous agents or accessing our neural processing API, you agree to be bound by these Master Service Terms and all documents referenced herein. These terms constitute a legally binding agreement between your organization and Aetheris Intelligence.
                </p>
              </div>
            </motion.div>

            <motion.div
               initial={{ opacity: 0, y: 20 }}
               whileInView={{ opacity: 1, y: 0 }}
               viewport={{ once: true }}
               className="space-y-6"
            >
              <h2 className="text-2xl font-bold text-white flex items-center">
                <span className="text-blue-500 mr-3">02.</span> Acceptable Intelligence Use
              </h2>
              <div className="prose prose-zinc prose-invert max-w-none font-light leading-relaxed text-lg text-zinc-400">
                <p>
                  You are responsible for all conversational outputs generated by your agents. You may not use our services to:
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                   {[
                     "Automate deceptive marketing practices",
                     "Transmit malicious code via messaging",
                     "Bypass WhatsApp Business API policies",
                     "Train competing language models"
                   ].map((item, i) => (
                     <div key={i} className="flex items-center p-4 rounded-2xl bg-zinc-900/50 border border-white/5">
                        <AlertCircle className="w-4 h-4 text-red-500/50 mr-3" />
                        <span className="text-sm">{item}</span>
                     </div>
                   ))}
                </div>
              </div>
            </motion.div>

            <motion.div
               initial={{ opacity: 0, y: 20 }}
               whileInView={{ opacity: 1, y: 0 }}
               viewport={{ once: true }}
               className="space-y-6"
            >
              <h2 className="text-2xl font-bold text-white flex items-center">
                <span className="text-blue-500 mr-3">03.</span> Compute Resources & SLAs
              </h2>
              <div className="prose prose-zinc prose-invert max-w-none font-light leading-relaxed text-lg text-zinc-400">
                <p>
                  We provide elastic compute resources based on your subscription tier. Enterprise clients are governed by a separate Service Level Agreement (SLA) providing 99.99% uptime for conversational processing.
                </p>
              </div>
            </motion.div>

            <motion.div
               initial={{ opacity: 0, y: 20 }}
               whileInView={{ opacity: 1, y: 0 }}
               viewport={{ once: true }}
               className="space-y-6"
            >
              <h2 className="text-2xl font-bold text-white flex items-center">
                <span className="text-blue-500 mr-3">04.</span> Termination
              </h2>
              <div className="prose prose-zinc prose-invert max-w-none font-light leading-relaxed text-lg text-zinc-400">
                <p>
                  Aetheris reserves the right to suspend neural processing nodes if usage patterns indicate a breach of security or a violation of Meta's WhatsApp Business Platform terms.
                </p>
              </div>
            </motion.div>

            <div className="p-8 rounded-[2rem] bg-blue-500/5 border border-blue-500/10 flex items-start space-x-6">
               <div className="p-3 bg-blue-500/20 rounded-xl">
                  <CheckCircle className="w-6 h-6 text-blue-400" />
               </div>
               <div>
                  <h4 className="text-white font-bold mb-2">Legal Consultation</h4>
                  <p className="text-sm font-light text-zinc-500 max-w-lg">If your organization requires custom legal riders or has specific procurement requirements, please contact our legal team at legal@aetheris.ai.</p>
               </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
